# Generated by Django 4.2.18 on 2026-02-25 11:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/')),
                ('employment_type', models.CharField(choices=[('full_time', "To'liq stavka"), ('part_time', 'Yarim stavka'), ('contract', 'Shartnoma asosida'), ('hourly', 'Soatbay')], default='full_time', max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, help_text="Asosiy oylik maosh (so'm)", max_digits=12)),
                ('work_start_date', models.DateField(blank=True, help_text='Ishga kirgan sana', null=True)),
                ('schedule', models.JSONField(blank=True, help_text='Haftalik ish jadvali', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('arrival_latitude', models.FloatField(blank=True, null=True)),
                ('arrival_longitude', models.FloatField(blank=True, null=True)),
                ('arrival_distance', models.FloatField(blank=True, help_text='Texnikumdan masofa (metr)', null=True)),
                ('arrival_type', models.CharField(choices=[('gps', 'GPS orqali'), ('manual', "Qo'lda (Admin)"), ('auto', 'Avto-chiqish (Tizim)')], default='gps', max_length=10)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('departure_latitude', models.FloatField(blank=True, null=True)),
                ('departure_longitude', models.FloatField(blank=True, null=True)),
                ('departure_type', models.CharField(choices=[('gps', 'GPS orqali'), ('manual', "Qo'lda (Admin)"), ('auto', 'Avto-chiqish (Tizim)')], default='gps', max_length=10)),
                ('late_minutes', models.IntegerField(default=0, help_text='Kechikkan daqiqalar soni')),
                ('early_leave_minutes', models.IntegerField(default=0, help_text='Erta ketgan daqiqalar')),
                ('status', models.CharField(blank=True, max_length=200)),
                ('employee_status', models.CharField(blank=True, help_text="O'sha kunda xodim holati (ISHDA, TATILDA...)", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xodim Davomati',
                'verbose_name_plural': 'Xodim Davomatlari',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('vacation', "Ta'tilda"), ('sick_leave', 'Kasal varaqasi'), ('business_trip', 'Xizmat safari'), ('day_off', 'Dam olish kuni (ruxsat bilan)'), ('unpaid_leave', "Haqsiz ta'til")], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField(blank=True, help_text='Sabab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xodim Holati',
                'verbose_name_plural': 'Xodim Holatlari',
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Ijara'), ('utilities', 'Kommunal (elektr, suv, gaz)'), ('salary', "Maosh to'lovi"), ('equipment', 'Jihozlar va inventar'), ('marketing', 'Reklama va marketing'), ('education', "O'quv materiallari"), ('transport', 'Transport'), ('other', 'Boshqa')], max_length=20)),
                ('title', models.CharField(help_text='Xarajat nomi', max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('receipt', models.ImageField(blank=True, help_text='Chek rasmi', null=True, upload_to='expenses/receipts/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Asosiy maosh', max_digits=12)),
                ('working_days', models.IntegerField(default=0, help_text='Ish kunlari soni (joriy oy)')),
                ('present_days', models.IntegerField(default=0, help_text='Kelgan kunlar soni')),
                ('late_minutes', models.IntegerField(default=0, help_text='Jami kechikish daqiqalari')),
                ('late_penalty', models.DecimalField(decimal_places=2, default=0, help_text="Kechikish jarimasi (so'm)", max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, help_text='Boshqa chegirmalar', max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, help_text="Qo'lga tegadigan summa", max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Hisoblandi (Tasdiqlanmagan)'), ('approved', 'Tasdiqlandi'), ('paid', "To'landi")], default='draft', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oylik Hisob-Kitob',
                'verbose_name_plural': 'Oylik Hisob-Kitoblar',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Texnikum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='texnikum/logos/')),
                ('latitude', models.FloatField(blank=True, help_text='Texnikum GPS kenglik', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Texnikum GPS uzunlik', null=True)),
                ('gps_radius', models.IntegerField(default=100, help_text='Davomat uchun radius (metr)')),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Texnikum',
                'verbose_name_plural': 'Texnikumlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('texnikum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app_texnikum.texnikum')),
            ],
        ),
    ]
