# Generated by Django 4.2.18 on 2026-02-25 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_texnikum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='app_texnikum.employee'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='texnikum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='app_texnikum.texnikum'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='texnikum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='app_texnikum.texnikum'),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='app_texnikum.employee'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app_texnikum.employee'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='texnikum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendances', to='app_texnikum.texnikum'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app_texnikum.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app_texnikum.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='texnikum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app_texnikum.texnikum'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='texnikum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='app_texnikum.texnikum'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('texnikum', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together={('employee', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('texnikum', 'name')},
        ),
    ]
