# Generated by Django 4.2.18 on 2026-02-25 11:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_texnikum', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: 1-IT-24', max_length=100)),
                ('schedule', models.JSONField(blank=True, help_text='Haftalik dars jadvali', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Guruh boshlanish sanasi', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Guruh tugash sanasi', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='app_texnikum.department')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('parent_name', models.CharField(blank=True, max_length=200)),
                ('parent_phone', models.CharField(blank=True, max_length=15)),
                ('student_id', models.CharField(blank=True, help_text='Talaba ID raqami', max_length=50)),
                ('enrollment_date', models.DateField(blank=True, help_text='Qabul qilingan sana', null=True)),
                ('study_status', models.CharField(choices=[('active', "O'qiydi"), ('expelled', 'Haydalgan'), ('graduated', 'Bitirgan'), ('academic', "Akademik ta'til"), ('transfer', "Ko'chirilgan")], default='active', max_length=15)),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0, help_text="Shartnoma summasi (so'm)", max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text="To'langan summa (so'm)", max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app_talaba.group')),
                ('texnikum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app_texnikum.texnikum')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hours', models.IntegerField(default=0, help_text='Jami soatlar')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('texnikum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='app_texnikum.texnikum')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['name'],
                'unique_together': {('texnikum', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Xona nomi, masalan: 101-xona', max_length=100)),
                ('capacity', models.IntegerField(default=30, help_text="Sig'imi (talabalar soni)")),
                ('is_active', models.BooleanField(default=True)),
                ('texnikum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='app_texnikum.texnikum')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'unique_together': {('texnikum', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Plastik karta'), ('transfer', "Bank o'tkazmasi")], default='cash', max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app_talaba.student')),
                ('texnikum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app_texnikum.texnikum')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('notif_type', models.CharField(choices=[('attendance', 'Davomat eslatmasi'), ('payment', "To'lov eslatmasi"), ('homework', 'Uy vazifasi'), ('announcement', "E'lon"), ('system', 'Tizim xabari')], default='announcement', max_length=15)),
                ('target_type', models.CharField(choices=[('all', 'Hammaga'), ('group', 'Guruhga'), ('student', 'Talabaga'), ('teacher', "O'qituvchiga"), ('staff', 'Xodimlarga')], default='all', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_talaba.group')),
                ('target_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_talaba.student')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('texnikum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app_texnikum.texnikum')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, help_text='Dars mavzusi', max_length=500)),
                ('homework', models.TextField(blank=True, help_text='Uy vazifasi')),
                ('note', models.TextField(blank=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app_talaba.group')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='app_talaba.room')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='app_talaba.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='app_texnikum.employee')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='app_talaba.room'),
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='app_talaba.subject'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text="Asosiy o'qituvchi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_groups', to='app_texnikum.employee'),
        ),
        migrations.AddField(
            model_name='group',
            name='texnikum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='app_texnikum.texnikum'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('homework', 'Uy vazifasi'), ('classwork', 'Dars ishi'), ('exam', 'Imtihon'), ('quiz', 'Nazorat ishi'), ('project', 'Loyiha')], max_length=15)),
                ('score', models.DecimalField(decimal_places=2, help_text='Ball (masalan: 85.5)', max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('date', models.DateField(default=datetime.date.today)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_grades', to='app_texnikum.employee')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='app_talaba.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='app_talaba.student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='app_talaba.subject')),
            ],
            options={
                'verbose_name': 'Baho',
                'verbose_name_plural': 'Baholar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('arrival_latitude', models.FloatField(blank=True, null=True)),
                ('arrival_longitude', models.FloatField(blank=True, null=True)),
                ('arrival_distance', models.FloatField(blank=True, help_text='Texnikumdan masofa (metr)', null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Keldi'), ('absent', 'Kelmadi'), ('late', 'Kechikdi'), ('excused', "Sababli yo'q"), ('left_early', 'Erta ketdi')], default='absent', max_length=15)),
                ('check_type', models.CharField(choices=[('gps', 'GPS orqali'), ('manual', "O'qituvchi tomonidan"), ('auto', 'Avto (tizim)')], default='gps', max_length=10)),
                ('note', models.TextField(blank=True, help_text="O'qituvchi izohi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='app_talaba.group')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app_talaba.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app_talaba.student')),
            ],
            options={
                'verbose_name': 'Talaba Davomati',
                'verbose_name_plural': 'Talabalar Davomati',
                'ordering': ['-date'],
                'unique_together': {('lesson', 'student')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('texnikum', 'name')},
        ),
    ]
